services:
  mariadb:
    build: ./requirements/mariadb
    env_file: 
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - adminer_data:/var/www/adminer:ro
    depends_on:
      - wordpress
      - adminer
    networks:
      - inception
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    secrets:
      - db_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: on-failure
  redis:
    build: ./requirements/bonus/Redis
    # ports:
    #   - "6379:6379"
    networks:
      - inception
    restart: on-failure
  adminer:
    build: ./requirements/bonus/Adminer
    volumes:
      - adminer_data:/var/www/adminer
    networks:
      - inception
    restart: on-failure
  ftp:
    build: ./requirements/bonus/FTP
    env_file:
      - .env
    ports:
      - "21:21"
    volumes:
      - wordpress_data:/home/yhajji/ftp
    networks:
      - inception
    secrets:
      - ftp_password
    restart: on-failure
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/yhajji/data/mariadb"
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/yhajji/data/wordpress"
  adminer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/yhajji/data/adminer"
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
networks:
  inception:
    driver: bridge